channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat >=0.8.0
- goosehdf5 >=0.21.0
- goosempl
- gooseslurm
- h5py
- numpy
- parallel
- pre-commit
- pybind11
- python
- python-cppcolormap
- python-frictionqpotspringblock >=0.20.0
- python-gooseeye
- python-goosefem >=1.1.0
- python-prrng >=1.7.2
- scikit-build
- setuptools_scm
- shelephant
- sphinx_rtd_theme
- tqdm
- xdmfwrite_h5py >=0.2.0
