channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat
- goosehdf5 >=0.17.1
- goosempl
- gooseslurm
- h5py
- parallel
- pre-commit
- python
- python-cppcolormap
- python-frictionqpotspringblock >0.15.2
- python-gooseeye
- python-goosefem >=1.1.0
- python-prrng
- python-qpot >=0.12.1
- setuptools_scm
- shelephant
- sphinx_rtd_theme
- tqdm
- xdmfwrite_h5py
- xsimd
