channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat >=0.9.1
- furo
- goosehdf5 >=0.22.0
- goosempl
- gooseslurm
- h5glance
- h5py
- mv_regex
- numpy
- parallel
- pdfcombine
- pre-commit
- prettytable
- pybind11
- pytest
- python >=3.11
- python-cppcolormap
- python-frictionqpotspringblock >=0.22.7
- python-gooseeye >=0.7.1
- python-goosefem >=1.1.0
- python-prrng >=1.11.0
- scikit-build
- setuptools_scm
- shelephant >=0.23.0
- sphinx
- sphinx-argparse
- sphinx_rtd_theme
- tqdm
- xdmfwrite_h5py >=0.2.0
