channels:
- conda-forge
dependencies:
- autodocsumm
- click
- enstat >=0.6.0
- goosehdf5 >=0.17.1
- goosempl
- gooseslurm
- h5py
- numpy
- parallel
- pre-commit
- pybind11
- python
- python-cppcolormap
- python-frictionqpotspringblock >=0.16.0
- python-gooseeye
- python-goosefem >=1.1.0
- python-prrng
- python-qpot >=0.12.1
- scikit-build
- setuptools_scm
- shelephant
- sphinx_rtd_theme
- tqdm
- xdmfwrite_h5py
