[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[project]
authors = [{name = "Tom de Geus", email = "tom@geus.me"}]
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
  "click",
  "enstat >= 0.9.1",
  "FrictionQPotSpringBlock >= 0.22.7",
  "GooseEYE >= 0.7.1",
  "GooseFEM >= 1.1.0",
  "GooseHDF5 >= 0.22.0",
  "h5py",
  "numpy",
  "prettytable",
  "prrng >= 1.11.0",
  "shelephant >= 0.23.0",
  "tqdm",
  "XDMFWrite_h5py >= 0.2.0",
  "pyyaml"
]
description = "Shell between data and FrictionQPotSpringBlock"
dynamic = ["version"]
name = "data_inertia_2024"
readme = "README.md"
requires-python = ">=3.6"

[project.scripts]
Dynamics_AverageSystemSpanning = "Dynamics:_AverageSystemSpanning_cli"
Dynamics_Run = "Dynamics:_Run_cli"
EventMap_Info = "EventMap:_Info_cli"
EventMap_Paraview = "EventMap:_Paraview_cli"
EventMap_Plot = "EventMap:_Plot_cli"
EventMap_Run = "EventMap:_Run_cli"
Flow_EnsemblePack = "Flow:_EnsemblePack_cli"
Flow_Generate = "Flow:_Generate_cli"
Flow_Plot = "Flow:_Plot_cli"
Flow_Run = "Flow:_Run_cli"
QuasiStatic_CheckData = "QuasiStatic:_CheckData_cli"
QuasiStatic_CheckDynamics = "QuasiStatic:_CheckDynamics_cli"
QuasiStatic_CheckFastLoad = "QuasiStatic:_CheckFastLoad_cli"
QuasiStatic_EnsembleInfo = "QuasiStatic:_EnsembleInfo_cli"
QuasiStatic_ForceCurrentDataVersion = "QuasiStatic:_ForceCurrentDataVersion_cli"
QuasiStatic_Generate = "QuasiStatic:_Generate_cli"
QuasiStatic_GenerateFastLoad = "QuasiStatic:_GenerateFastLoad_cli"
QuasiStatic_JobRerun = "QuasiStatic:_JobRerun_cli"
QuasiStatic_Paraview = "QuasiStatic:_Paraview_cli"
QuasiStatic_Plot = "QuasiStatic:_Plot_cli"
QuasiStatic_PlotStateAfterSystemSpanning = "QuasiStatic:_PlotStateAfterSystemSpanning_cli"
QuasiStatic_Run = "QuasiStatic:_Run_cli"
QuasiStatic_StateAfterSystemSpanning = "QuasiStatic:_StateAfterSystemSpanning_cli"
QuasiStatic_StructureAfterSystemSpanning = "QuasiStatic:_StructureAfterSystemSpanning_cli"
QuasiStatic_UpdateData = "QuasiStatic:_UpdateData_cli"
Relaxation_EnsembleInfo = "Relaxation:_EnsembleInfo_cli"
Relaxation_Run = "Relaxation:_Run_cli"
Trigger_CheckData = "Trigger:_CheckData_cli"
Trigger_EnsembleInfo = "Trigger:_EnsembleInfo_cli"
Trigger_FilterCompleted = "Trigger:_FilterCompleted_cli"
Trigger_Generate = "Trigger:_Generate_cli"
Trigger_JobRerun = "Trigger:_JobRerun_cli"
Trigger_Merge = "Trigger:_Merge_cli"
Trigger_MergeBatch = "Trigger:_MergeBatch_cli"
Trigger_Paraview = "Trigger:_Paraview_cli"
Trigger_Run = "Trigger:_Run_cli"
Trigger_UpdateData = "Trigger:_UpdateData_cli"

[project.urls]
Source = "https://github.com/tdegeus/depinning_inertia_2024"

[tool.setuptools_scm]
write_to = "depinning_inertia_2024/_version.py"
