name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.code }}
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout prrng
      uses: actions/checkout@v3
      with:
        repository: tdegeus/prrng
        path: prrng

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        cache-env: true
        extra-specs:
          xtensor-python
          boost

    - name: Set dummy version
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=0.0" >> $GITHUB_ENV

    - name: Build python-prrng locally
      working-directory: prrng
      run: python -m pip install . -v

    - name: Install plot style
      run: python -c "import GooseMPL; GooseMPL.copy_style()"

    - name: Install module
      run: python -m pip install . -v

    - name: Run tests
      run: python -m unittest discover tests -v
